### PR TITLE
Addition of my Name

### PR DESCRIPTION
**Pull request by PaxEmmanuel**
I just filled the blank spaces across my name

### CODE REVIEW

**Comment by rwest** [comment]
You didn't *quite* follow the instructions - you made the changes on your `master` branch instead of creating a new branch with a different name. Not a big deal in this case, but as a general policy it's best to make your changes on what's usually called a "topic" branch - in case you wish to work on more than one topic at a time, before the pull request gets merged.

**Comment by PaxEmmanuel** [comment]
I suspected that I did not do something right
Should I create a branch and send another pull request?

**Comment by rwest** [comment]
No need. just letting you know. I've merged it fine.

**Comment by PaxEmmanuel** [comment]
Noted 
Thank you

**Pull request merged**
